language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10
  - oraclejdk11
  - openjdk11

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk11
  - jdk: openjdk11

script: mvn clean install
