language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10
  - oraclejdk11
  - openjdk11

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk11
  - jdk: openjdk11

script: mvn clean install

notifications:
  email:
    on_success: never
    on_failure: change
    on_start: never
  irc:
    channels:
      - "chat.freenode.net#nicoulaj"
    on_success: always
    on_failure: always
    on_start: never
    use_notice: true
